<?php
	if(!defined('APP')) die('...');

	/*
	* Kaynaklarım:
	* https://www.webmasterworld.com/search_engine_spiders/4849056.htm
	* https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/_generator_lists/good-user-agents.list
	* https://github.com/bluedragonz/bad-bot-blocker
	* https://github.com/areebmajeed/wordpress-anti-content-theft
	* https://wordpress.org/plugins/stopbadbots/
	*/

	if(RC_BadBotBlock == 1 && $_SESSION[SES]['allowed'] <> 1)
	{
		$bot_allowed = array(
			/**
			* https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/_generator_lists/good-user-agents.list
			* adresi kullanılarak oluşturulmuştur
			* liste harici eklenenler --- ile ayrılmıştır
			*/

			#listeden EKLENMEYEN veya BANLANANLAR
			/**
			* aolbuild, DoCoMo, Googlebot/Test, Google-HTTP-Java-Client, Gravityscan, gsa-crawler, Jakarta Commons,
			* Kraken/0.1, LinkedInBot, Slackbot, Slackbot-LinkExpanding, SAMSUNG, teoma, yahoo, Wordpress
			*/

			#---listeden eklenenler ---
			'adidxbot',
			'adsbot-google',
			'bingbot',
			'bingpreview',
			'duckduckgo',
			'facebookexternalhit',
			'Feedfetcher-Google',
			'Googlebot',
			'Googlebot-Image',
			'Googlebot-Mobile',
			'Googlebot-News',
			'Googlebot-Video',
			'GoogleImageProxy',
			'Google-AMPHTML',
			'Mediapartners-Google',
			'msnbot',
			'msnbot-media',
			'Yandexbot',
			'YandexMobileBot',
			'YandexImages/',
			'YandexImageResizer',
			'YandexMetrika',
			'YandexVideoParser',
			'YandexAccessibilityBot',
			'Slurp',
			'Yahoo! Slurp',
			'Twitterbot',
			#--- liste harici eklenenler ---
			'Alexabot',
			'WhatsApp',
			'Applebot',
			'pinterestbot',
			'Google Favicon',						#google favicon
			'developers.google.com/+/web/snippet/', #google snippet
			'WWW::Shorten::TinyURL',				#twitter tiny url
			#--- kendi botlarımız ----
			'SuperHaber/',
			'HaberiYakala/',
			'KupTekno/',
		);

		$bot_tested_banned = array(
			/*
			* WARNING
			* 3 önemli kelime yasak listesinden çıkartılmıştır, sakın yeniden ekleme
			* fdm / fq / disco
			*/
			'Firefox/7.0.',
			'MSIE 6.0',
			'360spider',
			'admantx',
			'AhrefsBot/',
			'evc-batch',
			'HybridBot',
			'Jorgee',
			'linkdexbot',
			'MetaURI',
			'Needle',
			'Netvibes',
			'SocialRankIOBot',
			'Scrapy',
			'zgrab',
			'qwantify/',
			'PyCurl',
			'Indy Library',
			'Getintent',
			'Ltx71',
			'Extractor',
			#--- kendi bot listemden aktardıklarım ----
			'archive.org_bot',
			'Mail.RU_Bot/',
			'CPython/',
			'GuzzleHttp/',
			'curl/',
			'wget/',
			'PHP/5',
			'PHP/7',
			'Moreover/',
			'newspaper',
			'AA-Crawler/',
			'node-superagent/',
			'YaK/',
			'Haberlerdenevar/',
			'stagefright/',
			'SimplePie/',
			'ApacheBench',
			'Go-http-client/',
			'scalaj-http/',
			'okhttp/',
			'LivelapBot/',
			'PicoFeed/',
			'istellabot/',
			'JoBo/',
			'omgili/',
			'Yeti/',
			'oBot/',
			'Feedly/',
			'FeedlyBot/',
			'AlphaBot/',
			'um-FC/',
			'MaxPointCrawler/',
			'GroupHigh/',
			'FeedBurner/',
			'Luminator-ur/',
			'Symfony BrowserKit',
			'MTM bot',
			'Google-Apps-Script',
			'ia_archiver',
			'special_archiver',
			'Mediatoolkitbot',
			'Nutch',
			'ShortLinkTranslate',
			'Laserlikebot/',
			'socialmediascanner',
			'Python-urllib/',
			'PaperLiBot/',
			'QOSHE/',
			'/epicbot',
			'BomboraBot/',
			'uCrawler/',
			'James Bot',
			'python-requests/',
			'DotBot/',
			'HepBulurBot/',
			'Codewisebot/',
			'TweetmemeBot/',
			'Diffbot/',
			'adbeat_bot',
			'Cliqzbot/',
			'POE-Component-Client-HTTP',
			'SkypeUriPreview',
			'Asparagus',
			'FlipboardProxy/',
			'um-LN/',
			'Baiduspider/',
			'Photon/',
			'Bot.Bul.Com.Tr/',
			'Aol Reader/',
			'WordPress/',
			'Faveeo/',
			'PocketParser/',
			'scraper',
			'NTENTbot',
			'Anonymouse',
			'lknsuite monitoring bot',
			'ApacheManifoldCFRSSFeedReader',
			'WebCrawler',
			'SMTBot',
			'Quiboat',
			'Mozilla/4.0 (compatible; Synapse)',
			'googlebot.com',
			'collection@infegy.com',
			'Snacktory',
			'EveryoneSocialBot/',
			'Yaani/',
			'sysscan/',
			'XoviBot/',
			'Heritrix',
			'URL Expander',
			'Slackbot-LinkExpanding',
			'domain/',
			'FuturiBot/',
			'dlvr.it',
			'Digg Deeper/',
			'AdsTxtCrawler/',
			'Sucker',
			'mediawords',
			'Gluten Free Crawler/',
			'YisouSpider',
			'son-magazin.com',
			'proximic',
			'CakePHP',
			'Astute',
			'Genieo/',
			'DnyzBot/',
			'LinqiaMetadataDownloaderBot/',
			'BegunAdvertising/',
			'Embedly/',
			'GrapeshotCrawler/',
			'SurdotlyBot/',
			'ToutiaoSpider/',
			'NewShareCounts',
			'XenForo',
			'datagnionbot',
			'lwp-request',
			'libcurl',
			'libwww-perl',
			'NetcraftSurveyAgent',
			'yahoo-ad-monitoring',
			'node-fetch/',
			'batch-crawler',
			'Exabot/',
			'Crowsnest/',
			'AndroidDownloadManager',
			'jetsli.de/crawler',
			'Automattic Feed Fetcher',
			'coccocbot',
			'Daum/',
			'MJ12bot/',
			'Deusu/',
			'BLEXBot/',
			'BUbiNG',
			'SemrushBot',
			'SEOkicks-Robot',
			'SiteExplorer/',
			'spbot/',
			'Uptimebot/',
			'CCBot/',
			'magpie-crawler',
			'trendictionbot',
			'rogerbot',
			'AviraScout/',
			'PhantomJS/',
			'crawler4j',
			'DomainCrawler',
			'GarlikCrawler',
			'MojeekBot',
			'SafeDNSBot',
			'SemanticScholarBot',
			'SurveyBot (DomainTools)',
			'VeriCiteCrawler',
			'Wotbox',
			'Sogou web spider',
		);

		$bot_mylist = array(
			'Baiduspider',		#yasaklandı ama benzer isim kullanan çıkabilir
			'WAP-Browser',
			'xxx',
			'AppEngine',
			'ZoomBot',
			'Survey',
			'HTTPClient',
			'webauth@cmcm.com',
			'google-http-java-client/',
			'showyoubot',
			'ichiro',
			'naverbot',
			'sogou',
			'youdaobot',
			'youdaobot-image',
			'java/1',
			'php/',
			'something',
			'apple-pubsub',
			'gnowitnewsbot',
			'ahrefs',
			'apache-httpclient',
			'moget',

			#--- az güvenilir  bir diğer ek liste -------------------
			# https://github.com/bluedragonz/bad-bot-blocker

			'EmailWolf',
			'clsHTTP',
			'Mirror',
			'Missigua Locator',
			'MozillaNEWT',
			'PHP version tracker',
			'Webclipping',
			'WebEMailExtrac',

			#--- az güvenilir  bir diğer ek liste -------------------
			# https://github.com/areebmajeed/wordpress-anti-content-theft

			'aqua_products',
			'baidubot',
			'blackhole',
			'bookmarksearchtool',
			'copernic',
			'dumbot',
			'enterprise_search',
			'fairadclient',
			'flamingattackbot',
			'grub-client',
			'hatenaantenna',
			'httplib',
			'iron33',
			'keyworddensity',
			'kenjinspider',
			'matahari',
			'misterpix',
			'morfeus',
			'netants',
			'offlineexplorer',
			'openbot',
			'oracleultrasearch',
			'perman',
			'radiationretriever',
			'searchpreview',
			'teleport',
			'telesoft',
			'theintraformant',
			'tocrawl/',
			'urlcontrol',
			'url_spider_pro',
			'urlywarning',
			'websterpro',
			'xenu',
			'zeuslinkscout',
			'Titan',				#dikkat, boş yere Titanium Build yakalıyor

			//tam ua üstünden banladık
			//benzeri çıkabileceği için takipte tutuyoruz
			'null',
			'Ruby',
			'ZmEu',
			'Nuzzel',
			'www.ru',
			'buzztalk',
			'Scanbot',
		);

		$bot_limited = array(
			/*
			* WARNING
			* 3 önemli kelime yasak listesinden çıkartılmıştır, sakın yeniden ekleme
			*
			* fdm		çoklu kelime yakalıyor
			* fq 		çoklu kelime yakalıyor
			* disco 	discovery telefon modelini yakalıyor
			* rma 		normal kelimesini yakalıyor
			* zeus		telefon modelini yakalıyor
			*/
			/**
			* https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/_generator_lists/bad-user-agents.list
			* Kullanılarak oluşturulmuştur
			*/
			'80legs',
			'Abonti',
			'Aboundex',
			'Acunetix',
			'AIBOT',
			'AiHitBot',
			'Aipbot',
			'Alexibot',
			'Alligator',
			'AllSubmitter',
			'Anarchie',
			'Apexoo',
			'ASPSeek',
			'Asterias',
			'Attach',
			'autoemailspider',
			'BackDoorBot',
			'Backlink-Ceck',
			'backlink-check',
			'BacklinkCrawler',
			'BackStreet',
			'BackWeb',
			'Badass',
			'Bandit',
			'Barkrowler',
			'BatchFTP',
			'Battleztar Bazinga',
			'BBBike',
			'BetaBot',
			'Bigfoot',
			'Bitacle',
			'Blackboard',
			'Black Hole',
			'BlackWidow',
			'Blow',
			'BlowFish',
			'Boardreader',
			'Bolt',
			'BotALot',
			'Brandprotect',
			'Brandwatch',
			'Buddy',
			'BuiltBotTough',
			'BuiltWith',
			'Bullseye',
			'BunnySlippers',
			'BuzzSumo',
			'Calculon',
			'CATExplorador',
			'CazoodleBot',
			'Cegbfeieh',
			'CheeseBot',
			'CherryPicker',
			'ChinaClaw',
			'Chlooe',
			'Claritybot',
			'Cloud mapping',
			'Cogentbot',
			'cognitiveseo',
			'Collector',
			'plumanalytics',
			'Copier',
			'CopyRight',
			'Copyscape',
			'Cosmos',
			'Craftbot',
			'CrazyWebCrawler',
			'Crescent',
			'CSHttp',
			'Curious',
			'Custo',
			'DatabaseDriverMysqli',
			'DataCha0s',
			'DBLBot',
			'demandbase-bot',
			'Demon',
			'Devil',
			'Digincore',
			'DIIbot',
			'Dirbuster',
			'Discobot',
			'Discoverybot',
			'DittoSpyder',
			'DomainAppender',
			'DomainSigmaCrawler',
			'DomainStatsBot',
			'Download Wonder',
			'Dragonfly',
			'DTS Agent',
			'EasyDL',
			'Ebingbong',
			'eCatch',
			'ECCP/',
			'Ecxi',
			'EirGrabber',
			'EMail Wolf',
			'EroCrawler',
			'Evil',
			'Extreme Picture Finder',
			'EyeNetIE',
			'Ezooms',
			'FHscan',
			'Fimap',
			'FlashGet',
			'Flunky',
			'Foobot',
			'Freeuploader',
			'FrontPage',
			'Fyrebot',
			'GalaxyBot',
			'Genieo',
			'GermCrawler',
			'GetRight',
			'GetWeb',
			'Gigablast',
			'Gigabot',
			'G-i-g-a-b-o-t',
			'Go-Ahead-Got-It',
			'Gotit',
			'GoZilla',
			'Go!Zilla',
			'Grabber',
			'GrabNet',
			'Grafula',
			'GrapeFX',
			'GridBot',
			'GT::WWW',
			'HaosouSpider',
			'Harvest',
			'Havij',
			'HEADMasterSEO',
			'Hloader',
			'HMView',
			'HTMLparser',
			'HTTP::Lite',
			'HTTrack',
			'Humanlinks',
			'Iblog',
			'IDBot',
			'Id-search',
			'IlseBot',
			'Image Sucker',
			'InfoNaviRobot',
			'InfoTekies',
			'instabid',
			'Intelliseek',
			'InterGET',
			'Internet Ninja',
			'InternetSeer',
			'internetVista monitor',
			'Iria',
			'IRLbot',
			'Iskanie',
			'JamesBOT',
			'Jbrofuzz',
			'JennyBot',
			'JetCar',
			'JikeSpider',
			'JOC Web Spider',
			'Joomla',
			'JustView',
			'Jyxobot',
			'Kenjin Spider',
			'Keyword Density',
			'Kozmosbot',
			'Lanshanbot',
			'Larbin',
			'LeechFTP',
			'LeechGet',
			'LexiBot',
			'Lftp',
			'LibWeb',
			'Libwhisker',
			'Lightspeedsystems',
			'Likse',
			'LinkpadBot',
			'LinkScan',
			'LinksManager',
			'LinkWalker',
			'LinqiaRSSBot',
			'LinqiaScrapeBot',
			'Lipperhey',
			'Litemage_walker',
			'Lmspider',
			'LNSpiderguy',
			'LWP::Simple',
			'lwp-trivial',
			'Magnet',
			'Mag-Net',
			'Mail.ru',
			'Majestic12',
			'MarkMonitor',
			'MarkWatch',
			'Masscan',
			'Mass Downloader',
			'Mata Hari',
			'Meanpathbot',
			'MFC_Tear_Sample',
			'Microsoft Data Access',
			'Microsoft URL Control',
			'MIDown tool',
			'MIIxpc',
			'Mister PiX',
			'Mojeek',
			'MSFrontPage',
			'MSIECrawler',
			'Msrabot',
			'MS Web Services Client Protocol',
			'Musobot',
			'Name Intelligence',
			'Nameprotect',
			'Navroad',
			'NearSite',
			'Nessus',
			'Netcraft',
			'netEstate NE Crawler',
			'NetLyzer',
			'NetMechanic',
			'NetSpider',
			'Nettrack',
			'Net Vampire',
			'NetZIP',
			'NextGenSearchBot',
			'Nibbler',
			'NICErsPRO',
			'Niki-bot',
			'Nikto',
			'NimbleCrawler',
			'Ninja',
			'Nmap',
			'NPbot',
			'Octopus',
			'Offline Explorer',
			'Offline Navigator',
			'Openfind',
			'OpenLinkProfiler',
			'Openvas',
			'OrangeBot',
			'OrangeSpider',
			'OutfoxBot',
			'PageAnalyzer',
			'Page Analyzer',
			'PageGrabber',
			'page scorer',
			'PageScorer',
			'Panscient',
			'Papa Foto',
			'Pavuk',
			'pcBrowser',
			'PECL::HTTP',
			'PeoplePal',
			'PHPCrawl',
			'Picscout',
			'Picsearch',
			'PictureFinder',
			'Pimonster',
			'Pi-Monster',
			'Pixray',
			'PleaseCrawl',
			'Pockey',
			'POE-Component-Client-HTTP',
			'Probethenet',
			'ProPowerBot',
			'ProWebWalker',
			'Psbot',
			'Pump',
			'QueryN Metasearch',
			'RankActive',
			'RankFlex',
			'RankingBot',
			'RankingBot2',
			'Rankivabot',
			'RankurBot',
			'RealDownload',
			'Reaper',
			'RebelMouse',
			'Recorder',
			'RedesScrapy',
			'ReGet',
			'RepoMonkey',
			'Ripper',
			'RocketCrawler',
			'SalesIntelligent',
			'SBIder',
			'ScanAlert',
			'Screaming',
			'ScreenerBot',
			'Searchestate',
			'SearchmetricsBot',
			'Semrush',
			'SEOlyticsCrawler',
			'Seomoz',
			'SEOprofiler',
			'seoscanners',
			'SEOstats',
			'sexsearcher',
			'Seznam',
			'Siphon',
			'SISTRIX',
			'Sitebeam',
			'Siteimprove',
			'SiteLockSpider',
			'SiteSnagger',
			'SiteSucker',
			'Sitevigil',
			'SlySearch',
			'SmartDownload',
			'Snake',
			'Snapbot',
			'Snoopy',
			'Sosospider',
			'Sottopop',
			'SpaceBison',
			'Spammen',
			'SpankBot',
			'Spanner',
			'Spinn3r',
			'SputnikBot',
			'Sqlmap',
			'Sqlworm',
			'Sqworm',
			'Steeler',
			'Stripper',
			'Sucuri',
			'SuperBot',
			'SuperHTTP',
			'Surfbot',
			'Suzuran',
			'Swiftbot',
			'sysscan',
			'Szukacz',
			'T0PHackTeam',
			'T8Abot',
			'tAkeOut',
			'Telesphoreo',
			'Telesphorep',
			'The Intraformant',
			'TheNomad',
			'TightTwatBot',
			'Toata',
			'Toweyabot',
			'Trendiction',
			'True_Robot',
			'Turingos',
			'Turnitin',
			'TurnitinBot',
			'TwengaBot',
			'Twice',
			'Typhoeus',
			'UnisterBot',
			'URLy.Warning',
			'URLy Warning',
			'Vacuum',
			'Vagabondo',
			'VB Project',
			'VCI',
			'Virusdie',
			'VoidEYE',
			'Voil',
			'Voltron',
			'Wallpapers/3.0',
			'WallpapersHD',
			'WASALive-Bot',
			'WBSearchBot',
			'Webalta',
			'WebAuto',
			'Web Auto',
			'WebCollage',
			'Web Collage',
			'WEBDAV',
			'WebEnhancer',
			'Web Enhancer',
			'WebFuck',
			'Web Fuck',
			'WebGo IS',
			'WebLeacher',
			'WebmasterWorldForumBot',
			'webmeup-crawler',
			'WebPix',
			'Web Pix',
			'WebReaper',
			'WebSauger',
			'Web Sauger',
			'Webshag',
			'WebsiteQuester',
			'Website Quester',
			'Webster',
			'WebWhacker',
			'WebZIP',
			'WeSEE',
			'Whack',
			'Whacker',
			'Whatweb',
			'Who.is',
			'Who.is Bot',
			'Widow',
			'WinHTTrack',
			'WiseGuys Robot',
			'WISENutbot',
			'Wonderbot',
			'Woobot',
			'Wprecon',
			'WPScan',
			'WWW-Mechanize',
			'WWW::Mechanize',
			'WWWOFFLE',
			'x09Mozilla',
			'x22Mozilla',
			'Xaldon_WebSpider',
			'Xaldon WebSpider',
			'YoudaoBot',
			'Zade',
			'Zermelo',
			'Zitebot',
			'ZumBot',
			'ZyBorg',
		);

		$bot_stopbadbots = array(
			'0.9xpre12',
			'007AC9',
			'01NET.COM',
			'15miles',
			'2.xpre7',
			'200PleaseBot',
			'2Bone',
			'2locosbot',
			'3W1bot',
			'404 Checker',
			'404checker',
			'440network',
			'4algeria',
			'4SeoHuntBot',
			'50.nu',
			'5Bot',
			'a3logics',
			'A6-Indexer',
			'Abacho',
			'abby',
			'ABCdatos',
			'abonti.com',
			'aboutthedomain',
			'AboutUsBot',
			'Abrave Spider',
			'Accelobot',
			'Accoona-AI-Agent',
			'AcoiRobot',
			'acontbot',
			'AcoonBot',
			'acrylicapps',
			'adbeat',
			'Adbeat bot',
			'ADBot',
			'AddThis',
			'AddThis.com',
			'AdnormCrawler',
			'AdoSpeaker',
			'adressendeutschland.de',
			'ADSARobot',
			'AdvBot',
			'AESOP_com_SpiderMan',
			'affiliatewindow',
			'agentslug',
			'Aggregator',
			'ah-ha',
			'Ahoy! The Homepage Finder',
			'aiohttp',
			'Airmail',
			'AITCSRobot',
			'akula',
			'alertra',
			'Alibaba',
			'almaden',
			'alternatehistory',
			'alyze.info',
			'amagit',
			'Amagit.COM',
			'americanfoodbloggers',
			'Amfibibot',
			'amibot',
			'AMZNKAssocBot',
			'Analyzer',
			'AndersPinkBot',
			'AnDOSid',
			'Anemone',
			'AnswerBus',
			'AntBot',
			'Anthill',
			'antibot',
			'Anturis',
			'Anturis Agent',
			'AnyEvent',
			'AnzwersCrawl',
			'Apercite',
			'Aport',
			'AportWorm',
			'appie',
			'AppleNewsBot',
			'AraBot',
			'Arachmo',
			'arachnode',
			'arachnode.net',
			'Arachnoidea',
			'Arachnophilia',
			'Arameda',
			'Aranea',
			'Araneo',
			'ArchitextSpider',
			'archive',
			'Arellis',
			'argenfybot',
			'Argus',
			'aria2',
			'ArielisBot',
			'Art-Online',
			'ArthurHoaro',
			'asafaweb',
			'asafaweb.com',
			'Ask Jeeves',
			'AskQuickly',
			'AskTB',
			'Asperatusbot',
			'ASpider',
			'asynchttp',
			'atasift',
			'Atlas',
			'ATN_Worldwide',
			'Atomz',
			'Audisto Crawler',
			'AURESYS',
			'auskunftbot',
			'autocite',
			'Automattic Analytics Crawler',
			'Autonomy',
			'Avira crawler',
			'AwarioRssBot',
			'aweber.com',
			'aylienbot',
			'B-l-i-t-z-B-O-T',
			'b2w',
			'BabalooSpider',
			'BackRub',
			'Bad-Neighborhood',
			'Bait & Tackle',
			'banglalink',
			'baypup',
			'BazQux',
			'BCKLINKS',
			'BDCbot',
			'BebopBot',
			'BecomeBot',
			'BeetleBot',
			'beh1001',
			'beslist',
			'bibnum',
			'Big Brother',
			'BigBozz',
			'BigCliqueBOT',
			'biglotron',
			'Bimbot',
			'binlar',
			'bitlybot',
			'Bitrix',
			'bitvore.com',
			'bixocrawler',
			'biz_Directory',
			'Bizbot003',
			'BizBot04',
			'BizwikiBot',
			'bl.uk_lddc_bot',
			'Black.Hole',
			'BlekkoBot',
			'BlinkaCrawler',
			'blogbeat',
			'Bloglovin',
			'BlogPulse',
			'BlogPulseLive',
			'BlogSearch',
			'BlogsNowBot',
			'Blogtrottr',
			'BLP_bbot',
			'blubrry',
			'bluefish',
			'bnf.fr_bot',
			'Boatersbook',
			'boitho.com',
			'boitho.com bot',
			'boitho.com-dc',
			'boithocom-dc',
			'Bookmark',
			'borg-bot',
			'BOT for JCE',
			'bot-pge',
			'Bot.AraTurka.com',
			'bot.wsowner.com',
			'botmobi',
			'BotOnParade',
			'BotRightHere',
			'BotRobin',
			'BOTW Spider',
			'BPImageWalker',
			'BrainbruBot',
			'Braintree-Webhooks',
			'Branch',
			'Branch-Passthrough',
			'brandonmedia',
			'brightlocal',
			'BrokenLinkCheck.com',
			'Browsershots',
			'BrowserSpyBot',
			'BruinBot',
			'BSpider',
			'btbot',
			'BuckyOHare',
			'bumblebee',
			'BusinessBot',
			'Businessjet',
			'BusinessSeek.biz',
			'Butterfly',
			'Buzzbot',
			'C-T bot',
			'CACTVS',
			'CACTVS Chemistry Spider',
			'Calif',
			'CamontSpider',
			'CapsuleChecker',
			'CareerBot',
			'CaretNail',
			'carsopict.com',
			'Castabot',
			'CatchBot',
			'CBot',
			'CCGCrawl',
			'ccubee',
			'Cerberian',
			'Cerfinfo',
			'cg-eye',
			'ChangeDetection',
			'charlieapp',
			'Charlotte',
			'check-domains',
			'Check-Domains.com bot',
			'Check-Host',
			'Checkbot',
			'Checker',
			'checkgzipcompression.com robot',
			'CheckHost',
			'checklink',
			'CheckMarkNetwork',
			'Checksem',
			'ChimpFeedr',
			'chkme',
			'ChristCrawler.com',
			'cIeNcIaFiCcIoN.nEt',
			'CindooSpider',
			'CipinetBot',
			'CirrusExplorer',
			'CISPA',
			'CISPA Vulnerability Notificati',
			'citenikbot',
			'citygrid',
			'cityreview',
			'CJ.com crawler',
			'CJNetworkQuality',
			'ClarityDailyBot',
			'classbot',
			'Clickagy Intelligence Bot',
			'CligooRobot',
			'Climate Change Spider',
			'clips',
			'Closure Compiler Service',
			'CloudFlare-AlwaysOnline',
			'Cloudflare-Smart-Transit',
			'Cloudinary',
			'CloudServerMarketSpider',
			'cmcm',
			'CMS Crawler',
			'CMS Spider',
			'cmsworldmap.com',
			'coccoc',
			'COIBotParser',
			'CoinCornerBot',
			'colbert',
			'ColdFusion',
			'Collective',
			'comAgent',
			'combine',
			'CommaFeed',
			'CommonCrawler Node',
			'Commons-HttpClient',
			'Comodo',
			'Comodo-Webinspector-Crawler',
			'COMODOSpider',
			'Company News Search engine',
			'Companybook',
			'CompSpyBot',
			'Computer_and_Automation_Resear',
			'ConBot',
			'conceptbot',
			'contactbigdatafr',
			'Contacts Crawler',
			'contentDetection',
			'ContentScan',
			'ContextAd Bot',
			'contextadbot',
			'contxbot',
			'convera',
			'ConveraCrawler',
			'ConveraMultiMediaCrawler',
			'CoolBot',
			'CopperEgg',
			'CorpusCrawler',
			'CostaCider',
			'CouponBot',
			'Covario',
			'Covario-IDS',
			'Cowbot',
			'crawl',
			'CrawlConvera',
			'crawler for netopian',
			'crawler National Library of Is',
			'Crawlera',
			'CrawlForMe',
			'crawlingpolicy',
			'CrawlWave',
			'CRIM Crawler',
			'CrocCrawler',
			'CSS Certificate Spider',
			'CukBot',
			'curata.com',
			'curb',
			'Cusco',
			'cutbot.net',
			'cuwhois',
			'cxense',
			'CXL-FatAssANT',
			'CyberPatrol',
			'CyberPatrol SiteCat Webbot',
			'CyberPilot',
			'CyberSpyder',
			'cybo',
			'DareBoost',
			'DataFountains',
			'dataminr',
			'DataparkSearch',
			'dataprovider',
			'Daumoa',
			'DAWINCI ANTIPLAG',
			'Dazoobot',
			'DBot',
			'DCPbot',
			'Dead Link Checker',
			'deadlinkchecker',
			'DealGates Bot',
			'deepcrawl',
			'DeepIndex',
			'deepsearchnine',
			'Density',
			'DepSpid',
			'DER-bot',
			'DesertRealm.com',
			'devoll',
			'Deweb',
			'Dex Media Bot',
			'DF Bot',
			'DialogSearch.com',
			'DiamondBot',
			'Die Blinde Kuh',
			'DIE-KRAEHE',
			'dienstspider',
			'digg',
			'Digger',
			'digitalpebble',
			'disavowfiles',
			'DISCo Pump',
			'DISCoFinder',
			'Discordbot',
			'disqus',
			'DIY-SEOBot',
			'dj-research',
			'djbot',
			'DKIMRepBot',
			'DL2Bot',
			'dlcbot',
			'DM-Search',
			'DNAbot',
			'DNS-Digger',
			'DNS-Tools',
			'DNS-Tools Header-Analyzer',
			'DNSPod crawler',
			'DNSPod-reporting',
			'DocfuBot',
			'docoloc',
			'Domain Re-Animator Bot',
			'DomainDB',
			'DomainMacroCrawler',
			'domainsbot',
			'DomainsDB.net MetaCrawler',
			'DomainSONOCrawler',
			'DomainTunoCrawler',
			'Dot TK - spider',
			'Dotcom-Monitor bot',
			'dotSemantic',
			'Dow Jones Searchbot',
			'downforeveryoneorjustme',
			'Download',
			'DownloadBot',
			'Downloader',
			'downnotifier',
			'downnotifier.com monitoring',
			'DowntimeDetector',
			'DragonBot',
			'Drecombot',
			'DripfeedBot',
			'drkpi.com',
			'drupact',
			'DSearch',
			'DTAagent',
			'dubaiindex',
			'DWCP',
			'DWDS-crawler',
			'DwnldBot',
			'e-SocietyRobot',
			'EARTHCOM',
			'EasouSpider',
			'Easy-Thumb',
			'EasyBib AutoCite',
			'easycron',
			'EbiNess',
			'ec2linkfinder',
			'eCairn-Grabber',
			'Eco-Portal Spider',
			'eCommerceBot',
			'EdisterBot',
			'ElectricMonk',
			'elefent',
			'elfinbot',
			'EmailCollector',
			'EmailMarketingRobot',
			'EMC Spider',
			'emefgebot',
			'EMPAS_ROBOT',
			'emudesc',
			'energyexperts',
			'EnfinBot',
			'EnigmaBot',
			'ENLLE bot',
			'Environmental Sustainability S',
			'envolk',
			'equellaurlbot',
			'ES.NET',
			'Esribot',
			'esther',
			'eSyndiCat',
			'ETI SEO bot',
			'etoolsbot',
			'Eule-Robot',
			'EuripBot',
			'Eurobot',
			'europarchive',
			'eventax',
			'eventBot',
			'EventGuruBot',
			'EventMachine',
			'Evidon',
			'Evliya Celebi',
			'Evo Bot',
			'Evrinid',
			'ExactSearch',
			'ExactSeek',
			'Exalead',
			'ExaleadCloudview',
			'ExB Language Crawler',
			'Exbot',
			'Excel',
			'ExchangleBot',
			'exif-search',
			'Experibot',
			'ExpertSearchSpider',
			'Exploratodo',
			'explorersearch',
			'Express-soft',
			'EyeNetIE',
			'Ezooms',
			'EZResult',
			'Facebook external hit',
			'FacebookBot',
			'factbot',
			'FairAd Client',
			'fairshare',
			'Falconsbot',
			'fantomas',
			'Faraday',
			'FAST bot',
			'FAST-',
			'fastbot crawler',
			'FastBug',
			'FastCrawler',
			'FastProbe',
			'FatBot',
			'FauBot',
			'FavOrg',
			'Faxobot',
			'FDM_2',
			'FeastieBot',
			'Feed Wrangler',
			'Feedage',
			'Feedbin',
			'FeedBooster',
			'FeedBucket',
			'FeedBunch',
			'FeedCatBot',
			'FeedChecker',
			'FeedFinder',
			'feedjira',
			'FeedPress',
			'Feedspot',
			'Feedspotbot',
			'Feedster Crawler',
			'Feedwind',
			'feeltiptop',
			'FelixIDE',
			'femtosearch',
			'Fetch',
			'Fever',
			'FFbot',
			'FHscan',
			'fido/',
			'FileHound',
			'finbot',
			'FindABusinessThat',
			'Findexa Crawler',
			'findlink',
			'findlinks',
			'findthatfile',
			'Findxbot',
			'Fireball',
			'firmilybot',
			'Fish-Search-Robot',
			'Flaming AttackBot',
			'Flamingo_SearchEngine',
			'FlashGet',
			'flatlandbot',
			'FlickBot',
			'FlightDeckReportsBot',
			'FlipboardBot',
			'FlipboardBrowserProxy',
			'FlipboardRSS',
			'Flocke bot',
			'fluffy',
			'Fluffy the spider',
			'flunky',
			'flynxapp',
			'focusbot',
			'FollowSite Bot',
			'Foobot/',
			'Fooooo_Web_Video_Crawl',
			'forEach',
			'forensiq',
			'Forest Conservation Spider',
			'fouineur',
			'FoundSeoTool',
			'Francis',
			'Franklin_Locator',
			'Free_Link',
			'Freecrawl',
			'FreeFind',
			'freelinkexplorerbot',
			'freeloader',
			'FreeWebMonitoring',
			'FreeWebMonitoring SiteChecker',
			'FrontPage',
			'ftt2.com',
			'FuckOff',
			'fuelbot',
			'Fuerza',
			'Funnelback',
			'FunnelWeb',
			'FusionBot',
			'FyberSpider',
			'Fyrebot',
			'g2reader-bot',
			'GAChecker',
			'Gaisbot',
			'GalaxyBot',
			'ganarvisitas',
			'GatorWarmer',
			'gazz',
			'GC3pro',
			'gcreep',
			'geek-tools',
			'GeliyooBot',
			'Genderanalyzer',
			'general.useragent.override',
			'GenericBot-ax',
			'genevabot',
			'GentleSource',
			'GentleSource Short URL Checker',
			'GeoBot',
			'GeonaBot',
			'Gesco',
			'gestaltIconoclast',
			'GetBot',
			'GetFoundBot',
			'GetLinkInfo',
			'GetLinkInfo.com',
			'getprismatic',
			'GetProxi.es-bot',
			'getrequest',
			'GetRight',
			'GetSmart',
			'GetURL',
			'GetURL.rexx',
			'GetURLInfo',
			'GetWeb',
			'GetWeb!',
			'ghostery bot',
			'GIDBot',
			'GigablastOpenSource',
			'Gigabot',
			'Gigamega.bot',
			'Gimme60bot',
			'GimmeUSAbot',
			'GingerCrawler',
			'gipo-crawler',
			'Girafabot',
			'GLBot',
			'glindahl-cocrawler',
			'GloomarBot',
			'Go-Ahead-Got-It',
			'Go!Zilla',
			'gocrawl',
			'GOFORITBOT',
			'Golem',
			'goliatspider',
			'GomezAgent',
			'gonzo',
			'gooblog',
			'goodbarber',
			'goodreads',
			'Goodzer',
			'Goose',
			'GornKer',
			'GoSpotCheck',
			'GoSquared',
			'GoSquared-Status-Checker',
			'gosquared-thumbnailer',
			'gotit',
			'GotSiteMonitor',
			'GozaikBot',
			'Grabber',
			'GrabNet',
			'Grafula',
			'Grahambot',
			'Grammarly',
			'griffon',
			'Gromit',
			'GroschoBot',
			'GrubNG',
			'GSLFbot',
			'GTmetrix',
			'Gulliver',
			'Gulper',
			'gumgum',
			'GurujiBot',
			'GVC WEB crawler',
			'gvfs',
			'hacker',
			'Hailoobot',
			'HamBot',
			'HappyFunBot',
			'Harvest',
			'Hatena',
			'Hatena Antenna',
			'hawkReader',
			'Hazel',
			'HeadDump',
			'HEADMasterSEO',
			'Healthbot',
			'HeartRails_Capture',
			'HeartRailsBot',
			'Heimdall',
			'hello world',
			'HelpSpy',
			'HenryTheMiragoRobot',
			'Heurekabot',
			'hgrepurl',
			'hl_ftien_spider',
			'hledejLevne',
			'hledejLevne.cz',
			'hloader',
			'HMView',
			'Holmes',
			'HolmesBot',
			'Homerbot',
			'HomeTags',
			'Hometown Spider Pro',
			'HootSuite',
			'HootSuite crawler',
			'Hootsuite-WebFeed',
			'HooWWWer',
			'hosterstats',
			'hosterstats.com',
			'HostItCheap',
			'HostTracker',
			'hotpage.fr',
			'Hotzonu',
			'houzzbot',
			'htdig',
			'Html_Link_Validator_',
			'HTMLParser',
			'htrix',
			'HTTP_Compression_Test',
			'http_sample',
			'HTTP-Header-Abfrage',
			'http-kit',
			'HTTP-Tiny',
			'HttpComponents',
			'httphr',
			'HTTPMon',
			'HttpProxy',
			'httpscheck',
			'httpssites_power',
			'HTTPTEST',
			'httpunit',
			'HttpUrlConnection',
			'HTTrack',
			'Huaweisymantecspider',
			'HubPages',
			'HubSpot',
			'HubSpot Crawler',
			'humanlinks',
			'Hurdler',
			'HyperCrawl',
			'HyperZbozi',
			'HyperZbozi.cz Feeder',
			'HypeStat',
			'i am a stego',
			'I Robot',
			'i686-pc-linux',
			'iajaBot',
			'icat.co.th',
			'ICC-Crawler',
			'IceCat',
			'iCjobs',
			'IconSurf',
			'icsbot',
			'IDBot',
			'IdeelaborPlagiaat',
			'IDG',
			'idmarch',
			'IDwhois',
			'IEAutoDiscovery',
			'IECheck',
			'IEMozilla',
			'Iframely',
			'igdeSpyder',
			'iHWebChecker',
			'IlseBot',
			'IlTrovatore',
			'iltrovatore-setaccio',
			'Image Stripper',
			'image.kapsi.net',
			'ImageEngine',
			'Imagga',
			'ImaggaBot',
			'immediatenet thumbnails',
			'ImplisenseBot',
			'import.io',
			'Impressumscrawler',
			'inagist',
			'inagist.com url crawler',
			'inbound',
			'InbyBot',
			'IncyWincy',
			'InDesign',
			'index-of-tv',
			'InetURL',
			'infegy',
			'InfiniteSweeps',
			'Influencebot',
			'infobot',
			'InfociousBot',
			'infohelfer',
			'infomine.ucr.edu',
			'InfoNaviRobot',
			'Informant',
			'InfoSeek Robot',
			'Infoseek Sidewinder',
			'InfoSpiders',
			'InfoTekies',
			'InfoWizards',
			'INGRID',
			'InnerpriseBot',
			'inoreader.com',
			'inpwrd',
			'InstantSSL Browser',
			'integrishield',
			'Integrity',
			'integromedb',
			'intelium_bot',
			'Intelliseek',
			'Interdose AntiSpamBot',
			'InterGET',
			'InterNaetBoten',
			'Internet Cruiser Robot',
			'Internet Ninja',
			'internet_archive',
			'InternetSeer',
			'InternetSeer.com',
			'internetVista monitor',
			'Intraformant',
			'intraVnews',
			'IODC',
			'IOneSearch.bot',
			'IP2PhraseBot',
			'IPAddressGuideBot',
			'iprospect',
			'Ips Agent',
			'ips-agent',
			'IPTCBOT',
			'ipts.com',
			'ipv6-test.com validator',
			'iqdb',
			'Iria',
			'IRLbot',
			'Irokez',
			'Irokez.cz monitoring',
			'Is it up',
			'ISC Systems iRc Search',
			'ISC_Systems_iRc_Search',
			'isitup',
			'iskanie',
			'IsraeliSearch',
			'IssueCrawler',
			'it2media-domain-crawler',
			'ITI Spider',
			'IUSA Browser',
			'IXEbot',
			'iZSearch',
			'iZSearch.com',
			'Jabse.com Crawler',
			'JadynAveBot',
			'jagajam',
			'Jakarta',
			'JamesBOT',
			'janforman',
			'janforman.com',
			'jaribot',
			'JavaBee',
			'Jayde crawler',
			'JBH Agent',
			'Jcrawler/',
			'JennyBot',
			'JennyCar',
			'JetBot',
			'JetCar',
			'Jetty',
			'Jigsaw',
			'JikeSpider',
			'Job Roboter Spider',
			'Jobboerse',
			'JobboerseBot',
			'JobdiggerSpider',
			'JobKereso',
			'Jobot',
			'Jobrapido',
			'JOC',
			'JOC Web Spider',
			'johnhew crawler',
			'jooble',
			'jpg-newsbot',
			'JubiiRobot/',
			'jumpstation/',
			'JUST-CRAWLER',
			'justpicsplease',
			'JustView',
			'Jyxobot',
			'KakleBot',
			'KaloogaBot',
			'Karneval-Bot',
			'kasparek',
			'Kaspersky',
			'kastaneta',
			'Katipo/',
			'KAZ.KZ_Bot',
			'kazbtbot',
			'KcB',
			'KD Bot',
			'KDD-Explorer',
			'KeepRight',
			'KeepRight OpenStreetMap Checke',
			'Kemvibot',
			'Kenjin',
			'Kenjin Spider',
			'Kenjin.Spider',
			'KeyCDN bot',
			'Keyword Density',
			'Keyword.Density',
			'KickFire',
			'Kilroy',
			'KimonoLabs',
			'Kingbot',
			'kinshoo',
			'KIT-Fireball',
			'knowknot',
			'knowledge',
			'Knowledge.com',
			'knows',
			'KO_Yappo_Robot',
			'KOCMOHABT',
			'KOCMOHABT bot',
			'Kolibri',
			'KomodiaBot',
			'kouio',
			'KrOWLer',
			'Krzana',
			'kuloko-bot',
			'kulturarw',
			'kulturarw3',
			'KumKie',
			'Kumo',
			'Kwickbot',
			'Kyluka',
			'Kyoto-Crawler',
			'L.webis',
			'LabelGrab',
			'LABLEBot',
			'Labs',
			'lanshanbot',
			'LapozzBot',
			'larbin',
			'LDRbot',
			'leadcrunch',
			'Leadingcourses',
			'LeechFTP',
			'Leikibot',
			'leonosa',
			'LexiBot',
			'LexxeBot',
			'lftp',
			'librabot',
			'Library',
			'LibVLC',
			'libWeb',
			'Licorne Image Snapshot',
			'Liferea',
			'Lightspeedsystems',
			'Lijit',
			'likse',
			'lincobot',
			'linexsystems',
			'LinguaBot',
			'linguatools',
			'Linguee',
			'Linguee Bot',
			'LINK TRADE crawler',
			'Link Valet Online',
			'link_thumbnailer',
			'Link_Valet_Online',
			'LinkAider',
			'LinkAlarm',
			'LinkAnalyser',
			'linkapediabot',
			'linkbot',
			'linkCheck',
			'LinkCrier',
			'LinkedInBot',
			'LinkExaminer',
			'LinkExplore.com',
			'linkfluence',
			'linkis',
			'LinkLint',
			'linklooker',
			'Linkman',
			'LinkMarket-Bot',
			'LinkpadBot',
			'linkpeek',
			'LinkScan',
			'LinkStats Bot',
			'LinkTiger',
			'linkulator',
			'LinkVerifier',
			'LinkWalker',
			'linkwithin',
			'LinqiaBot',
			'Lipperhey SEO Service',
			'Lipperhey Spider',
			'Lipperhey-Kaus-Australis',
			'listonATccDOTgatechDOTedu',
			'LiteFinder',
			'livedoor ScreenShot',
			'lmspider',
			'LNSpiderguy',
			'LNSpiderguyt',
			'load-time',
			'LoadImpact',
			'LoadTimeBot',
			'LocalcomBot',
			'LongURL',
			'Look.com',
			'LookSeek',
			'looksystems',
			'Lorkyll',
			'LSSRocketCrawler',
			'ltbot',
			'lucideer',
			'lufsbot',
			'LuminateBot',
			'LumpImageSearch',
			'lwp',
			'lwp-trivial',
			'LWP::Simple',
			'LXRbot',
			'Lycos',
			'LYT.SR',
			'mabontland',
			'Mac_Finder',
			'MacInroy Privacy Auditors',
			'Mackster',
			'macsflowers',
			'Mag-Net',
			'MagiBot',
			'Magnet',
			'MagpieRSS',
			'Magus Bot',
			'MailChimp',
			'Majestic-12',
			'Majestic-SEO',
			'make.myUrl',
			'MaMa CaSpEr',
			'MaMa CyBer',
			'MaMa Xirio',
			'Mandrill',
			'manzama.com',
			'mapping',
			'MarcoPolo',
			'MarketBrewBot',
			'marketing',
			'marketinggrader',
			'marketwire',
			'MarkWatch',
			'MARTINI',
			'marvininfoseek',
			'MaSagool',
			'mashable',
			'Mass Downloader',
			'masscan',
			'Mata Hari',
			'Mata.Hari',
			'Matrix',
			'Maui Browser',
			'Mavicanet',
			'MB-SiteCrawler',
			'mbot',
			'meanpathbot',
			'Mechanize',
			'MediaBot',
			'MediaFox',
			'MediaLBot',
			'mediarithmics',
			'Mediumbot',
			'MegaIndex',
			'meltwater',
			'Melvil',
			'MeMoNewsBot',
			'memoryBot',
			'menv.com',
			'Mergadobot',
			'MergeFlow-PageReader',
			'MerzScope',
			'metacdn',
			'MetaCommentBot',
			'metadata-service',
			'MetaGeneratorCrawler',
			'metager2',
			'metager2-bot',
			'METAGOPHER',
			'MetaHeadersBot',
			'MetaInspector',
			'MetaJobBot',
			'MetamojiCrawler',
			'Metasearch',
			'METASpider',
			'Metaspinner',
			'metroguide',
			'MFC_Tear_Sample',
			'MFGPagesBot',
			'mfibot',
			'Mget',
			'MIA Bot',
			'MiaDev',
			'Microsearch',
			'Microsearch.ru Bot',
			'Microsoft_URL_Control',
			'Microsoft.URL',
			'MIDown',
			'MIDown tool',
			'MIIxpc',
			'Mindjet',
			'mindUpBot',
			'MinerBot',
			'Miniflux',
			'miniRank',
			'Mirago',
			'Missigua Locator',
			'Missigua_Locator',
			'Mister',
			'Mister PiX',
			'mitambo.com',
			'miva.com',
			'MixBot',
			'MixrankBot',
			'Mkzilla',
			'mlbot',
			'Mnogosearch',
			'moatbot',
			'moba-crawler',
			'mobileOK',
			'mogimogi',
			'Mojolicious',
			'MOMspider',
			'monitis',
			'Monitor',
			'Monitoring',
			'Monitority',
			'MonkeyCrawl',
			'MonoBot',
			'Monster',
			'montastic',
			'montastic-monitor',
			'MonTools',
			'MonTools.Com',
			'MoodleBot',
			'MOQU ADV crawlers',
			'MorMor TCP Spider',
			'Morning',
			'Morning Paper',
			'MotoMinerBot',
			'Motoricerca-Robots.txt-Checker',
			'movistar',
			'mowser',
			'mozDex',
			'Mp3Bot',
			'MPDP-ALR-Search-Bot',
			'MQbot',
			'MrakyPraceCzBot',
			'Mrcgiguy',
			'MS Cognitive Services',
			'mShots',
			'MSIECrawler',
			'MSMOBOT',
			'MSNPTC',
			'MSR-ISRCCrawler',
			'MSRBOT',
			'muckrack.',
			'multicrawler',
			'Multiviewbot',
			'MuscatFerret',
			'musobot',
			'mustexist.com',
			'MVAClient',
			'My User Agent',
			'My WinHTTP Connection',
			'My_WinHTTP_Connection',
			'My-Application',
			'my-robot',
			'MyAgent',
			'MyApp',
			'mycrawler',
			'MyUserAgent',
			'nagios',
			'Nail',
			'Najdi',
			'Najdi.si',
			'NalezenCzBot',
			'NameOfAgent',
			'NAMEPROTECT',
			'NationalDirectory',
			'NavissoBot',
			'Navroad',
			'nbertaupete95',
			'NCBot',
			'NCSA',
			'NCSA_Mosaic',
			'NearSite',
			'NEC-MeshExplorer',
			'Nekstbot',
			'Nelian Pty Ltd - Spider',
			'NeoScioCrawler',
			'NerdByNature.Bot',
			'NerdyBot',
			'Net Vampire',
			'NetCarta CyberPilot',
			'Netcraft',
			'Netcraft crawler',
			'netEstate',
			'netEstate Crawler',
			'netk6 crawler',
			'NetLyzer',
			'NetMechanic',
			'NetMind-Minder',
			'NetMonitor',
			'NetNewsWire',
			'NetNose',
			'Netpeak bot',
			'NetResearchServer',
			'NetScoop',
			'Netseer',
			'NetShelter',
			'NetShelter ContentScan',
			'Netsparker',
			'NetSpider',
			'NetSprint',
			'Nett.io bot',
			'Netthrob-bot',
			'NetTrack',
			'NetTrack.info bot',
			'Networking4all',
			'NetZIP',
			'NetZip-Downloader',
			'NetZippy',
			'NeumobBot',
			'Neustar',
			'Neustar WPM',
			'NeutrinoAPI',
			'newest.exe',
			'Newlyso',
			'news bot',
			'NewsBlur .*Finder',
			'NewsGator',
			'Newsgroupreporter_LinkCheck',
			'newsme',
			'NEWT',
			'NewUseAgent',
			'NextGenSearchBot',
			'NG-Search',
			'NHSEWalker',
			'nicebot',
			'NICErsPRO',
			'NIF',
			'Nigma.ru',
			'niki-bot',
			'Nikto',
			'NimbleCrawler',
			'nineconnections',
			'NING',
			'Ninja',
			'Nintindo Wii',
			'Nitro PDF Doaload',
			'NLCrawler',
			'NLNZ_IAHarvester',
			'nlpproject.info',
			'Nmap',
			'node',
			'nodestackbot',
			'Nomad',
			'nominet',
			'nomore404.com robot',
			'nonli',
			'Norton-Safeweb',
			'Notifixious',
			'notifyninja',
			'nowblogs.com',
			'noxtrumbot',
			'NPbot',
			'NRK-bruker',
			'nrsbot',
			'nubilosoft',
			'Nuesbyte',
			'nuhk',
			'Nusearch Spider',
			'nworm',
			'nWormFeedFinder',
			'Nymesis',
			'ObjectsSearch',
			'oBot',
			'oBot/',
			'Ocarinabot',
			'Occam',
			'Ocelli',
			'Octopus',
			'Octora_Beta',
			'OdklBot',
			'oebot',
			'oegp',
			'Offline',
			'Offline Explorer',
			'Offline Navigator',
			'Offline.Explorer',
			'OGspider',
			'oiqBot',
			'oku-taka-lab-bot',
			'OLE Control',
			'Omea',
			'OmniExplorer',
			'OmniExplorer_Bot',
			'Omnipelagos',
			'OmnizensBot',
			'OnetSzukaj',
			'Online Domain Tools',
			'online link validator',
			'online-webceo-bot',
			'OnPageBot',
			'OntoSpider',
			'oodlebot',
			'Open Text Site Crawler',
			'Open Web Analytics Bot',
			'OpenCalaisSemanticProxy',
			'Opendi Bot',
			'opendi.com',
			'Openfind',
			'Openfind data gathere',
			'Openfind data gatherer',
			'OpenfosBot',
			'OpenHoseBot',
			'OpenindexSpider',
			'OpenIntelligenceData',
			'Openstat',
			'OpenVAS',
			'OpenWebSpider',
			'Operabot',
			'OppO',
			'OptimizationCrawler',
			'Optimizer',
			'Oracle Ultra Search',
			'OrangeBot',
			'Orbiter',
			'OrgbyBot',
			'OrgProbe',
			'OsObot',
			'otway',
			'outbrain',
			'OutfoxBot',
			'Owler',
			'owlin.com',
			'ownCloud',
			'ownCloud Crawler',
			'PackRat',
			'PAD-bot',
			'Page Analyzer',
			'page scorer',
			'Page Valet',
			'page_verifier',
			'page2rss',
			'PageBitesHyperBot',
			'Pagebull',
			'PageGrabber',
			'PagePeeker',
			'PagesInventory',
			'Pagespeed',
			'Pajaczek',
			'Pandeo Bot',
			'Panopta',
			'Panopy Bot',
			'panscient',
			'panscient.com',
			'Papa',
			'Papa Foto',
			'ParchBot',
			'parsijoo',
			'parsijoo-bot',
			'Patric',
			'Patwebbot',
			'pavuk',
			'pcBrowser',
			'Pcore-HTTP',
			'pdffillerbot',
			'PEAR_HTTP_Request_class',
			'Pearltrees',
			'PeekBot',
			'Peeplo Screenshot Bot',
			'Peepowbot',
			'PEERbot',
			'peerindex',
			'Peew',
			'PercolateCrawler',
			'Performance',
			'Pete-Spider',
			'PGP-KA',
			'Phantom',
			'PhantomJS',
			'PHOTO CHECK',
			'PHP_version_tracker',
			'phpcrawl',
			'PhpDig',
			'phpservermon',
			'Pi-Monster',
			'PiltdownMan',
			'Pimptrain',
			'PINGOMETER',
			'Pingoscope',
			'PingSpot',
			'Pioneer',
			'pipeLiner',
			'PiplBot',
			'pirate',
			'pirst',
			'Pita',
			'Pixray-Seeker',
			'Pizilla',
			'plaNETWORK Bot Search',
			'PlantyNet',
			'Ploetz',
			'Plukkie',
			'PlurkBot',
			'pmafind',
			'pmoz.info ODP link checker',
			'pocketcasts',
			'Pockey',
			'podbean',
			'PodcastPartyBot',
			'poddirectory',
			'podparadise',
			'Poirot',
			'PolyBot',
			'Pompos',
			'Poodle_predictor',
			'Pooodle_predictor',
			'Popdexter',
			'PopScreen Bot',
			'Porkbun',
			'Port Monitor check service',
			'Port_Huron_Labs',
			'PortalJuice',
			'postano',
			'PostPost',
			'postrank',
			'PowerMapper Crawler',
			'pr-cy.ru Bot',
			'pragmaMx',
			'Prerender',
			'presspeople',
			'pressrush',
			'Priceonomics',
			'Priceonomics Analysis Engine',
			'Princetonbot',
			'PrintFriendly',
			'PritTorrent',
			'PrivacyAwareBot',
			'PrivateSearch',
			'Prlog',
			'probethenet',
			'probethenet.com scanner',
			'process',
			'ProCogBot',
			'ProCogSEOBot',
			'ProductoDownloadUrlBot',
			'profound',
			'Project 25499',
			'Promotion_Tools',
			'ProPowerBot',
			'prospectb2b',
			'Protopage',
			'ProWebWalker',
			'Proxad',
			'psbot',
			'psbot test for robots.txt',
			'psbot-page',
			'psycheclone',
			'PTST',
			'Pu_iN',
			'Pulsepoint',
			'Pump',
			'Purebot',
			'pushcrew',
			'PWBot',
			'PyQuery',
			'pyspider',
			'Pywikibot',
			'qingdao bieshu chushou',
			'Qirina',
			'Qirina Hurdler',
			'Qseero',
			'Qualidator',
			'Qualidator.com Bot',
			'QuepasaCreep',
			'QueryN Metasearch',
			'QueryN.Metasearch',
			'QuerySeekerSpider',
			'Quester',
			'quickobot',
			'QuickSproutBot',
			'Quora',
			'QuoraBot',
			'qwant.com',
			'QweeryBot',
			'r4Bot',
			'R6 bot',
			'R6_CommentReader',
			'RADaR-Bot',
			'Radian6',
			'Radiation Retriever',
			'RAMPyBot',
			'Random',
			'RankActive Bot',
			'RankFlex',
			'Ranking',
			'Ranking-Manager',
			'RankSonicSiteAuditor',
			'RankurBot',
			'RankvalBot',
			'ranscoder',
			'ratup.com',
			'Ravelry',
			'RavenCrawler',
			'Rawi',
			'RBSE Spider',
			'rcdtokyo',
			'Readability',
			'reader.aol.com',
			'RealDownload',
			'Reaper',
			'RebelMouse',
			'Recorder',
			'redback',
			'REDbot',
			'redditbot',
			'Redirect',
			'ReederForMac',
			'ReGet',
			'Regit',
			'REL_Link_Checker_Lite',
			'RelateIQ Crawler',
			'replaz',
			'RepoMonkey',
			'ResearchBot',
			'ResponseCodeTest',
			'RestSharp',
			'Resume Robot',
			'RetrevoPageAnalyzer',
			'retriever',
			'Riddler',
			'Riddlerbot',
			'ripper',
			'Rival',
			'Rival IQ',
			'RoboCrawl',
			'Robosourcer',
			'Robot',
			'Robot du CRIM',
			'Robot_txtChecker',
			'robot@monkia.com.tw',
			'roboto',
			'Robots_Tester',
			'RobotsChecker',
			'Robozilla',
			'robschecker',
			'Ronzoobot',
			'root',
			'rootlink',
			'ROR Sitemap Generator',
			'roswellspringcatalog',
			'Roverbot',
			'rssinclude',
			'RSSingBot',
			'RSSMicro.com',
			'Ruby',
			'RufusBot',
			'RukiCrawler',
			'Ruky-Roboter',
			'Runet-Research-Crawler',
			'rwth-aachen',
			'RX Bar',
			'RyzeCrawler',
			'SafeAds.xyz',
			'SafeAds.xyz bot',
			'SafeDNS search bot',
			'SafetyNet',
			'SafetyNet Robot',
			'SAI Crawler',
			'SalesIntelligent',
			'SandCrawler',
			'SANSARN',
			'SanszBot',
			'SauceNAO',
			'SBA Research bot',
			'SBIder',
			'SBL-BOT',
			'SBSearch',
			'scanner',
			'Scarlett',
			'SCFCrawler',
			'schibstedsokbot',
			'Schmozillav',
			'Scoop',
			'ScooperBot',
			'Scooter',
			'Scope (Mars+)',
			'Scopia crawler',
			'scour',
			'Scout',
			'ScoutJet',
			'ScoutURLMonitor',
			'ScreenerBot',
			'ScreenerBot Crawler',
			'ScreenShotService',
			'Screw-Ball',
			'script injection',
			'Scrubby',
			'scrutiny',
			'Search-10',
			'search-photo.info spider',
			'search.ch',
			'search.KumKie.com',
			'Search17Bot',
			'Searchmee!',
			'SearchmetricsBot',
			'SearchSight',
			'Searchspider',
			'SecretBrowser',
			'security analyser',
			'security scan',
			'SecurityResearchBot',
			'seegnifybot',
			'seek-crawler',
			'Seekbot',
			'sees',
			'seexie.com_bot',
			'Semager',
			'Semantic Health Web Crawler',
			'semantic-visions.com crawler',
			'semanticbot',
			'semanticdiscovery',
			'semanticjuice',
			'Semantifire',
			'semiocast',
			'Senrigan',
			'sensis',
			'Sensis Web Crawler',
			'Sensis.com.au Web Crawler',
			'SentiBot',
			'SEO Browser',
			'Seo Servis',
			'seo-audit-check-bot',
			'seo-nastroj',
			'seo-nastroj.cz',
			'Seobility',
			'SEOCentro',
			'SEOCentro bot',
			'seochat',
			'SeoCheck',
			'SeoCheckBot',
			'SEODat',
			'SEOdiver',
			'SEOENGBot',
			'SEOENGWorldBot',
			'Seologies',
			'SEOlyticsCrawler',
			'SEOlyzer',
			'SeopultContentAnalyzer',
			'SeoStackBot',
			'SEOstats',
			'Seoterritory',
			'Server Density',
			'servernfo',
			'servernfo.com',
			'ServiceUptime.robot',
			'Servis',
			'setcronjob',
			'Setoozbot',
			'sg-Orbiter',
			'Sgrunt',
			'ShagSeeker',
			'Shareaholicbot',
			'sharpr.com',
			'shelob',
			'Shim',
			'Shim-Crawler',
			'Shoppimon',
			'ShoppimonAgent',
			'shopping.com research',
			'ShopWiki',
			'shrinktheweb',
			'ShunixBot',
			'shybunnie-engine',
			'sideqik',
			'SideWinder',
			'SilverReader',
			'Simple',
			'SimplyFast',
			'SimplyFast.info',
			'simsalabim',
			'sistrix',
			'Site Crawler',
			'Site Valet',
			'Site-Shot',
			'Site24x7',
			'SiteAnalyze',
			'SiteAnalyzerBot',
			'SiteBar',
			'sitecheck.internetseer',
			'SiteCondor',
			'Sitedomain-Bot',
			'SiteGuardian',
			'Siteimprove',
			'Siteimprove.com bot',
			'SiteIntel.net Bot',
			'Siteliner',
			'sitelock',
			'SiteLockSpider',
			'Siteluxbot',
			'SiteProbe',
			'sitequest',
			'Siteshooter',
			'SiteSnagger',
			'SiteSpeedBot',
			'SiteSpider',
			'SiteTruth',
			'SiteTruth.com',
			'SiteWinder',
			'sitexy',
			'SiteXY Webmaster tools',
			'SKB Kontur bot',
			'Skroutz',
			'skygrid',
			'skyrock',
			'Slackbot',
			'slider',
			'SlySearch',
			'SlySearch test robots.txt',
			'SmabblerBot',
			'smart.apnoti.com Robot',
			'SmartDownload',
			'SmartLinksAddon',
			'SMPU',
			'SMRF',
			'SMTBot',
			'SMUrlExpander',
			'Sn4keVisor',
			'sna-',
			'Snake',
			'snap.com beta',
			'Snapbot',
			'Snappy',
			'SNAPSHOT',
			'Snarfer',
			'SniffRSS',
			'Snipebot',
			'snippet',
			'sniptracker',
			'Snooper',
			'Snoopy',
			'snprtz',
			'socialbm_bot',
			'softhub',
			'sohu-search',
			'Solbot',
			'SOLOFIELD bot',
			'solofield.net',
			'SolomonoBot',
			'SomePerlRobot',
			'sootle',
			'SortSite',
			'Sosospider',
			'sp_auditbot',
			'SpaceBison',
			'Spacebug',
			'spammer',
			'SpankBot',
			'spanner/',
			'spaziodati',
			'Specificfeeds',
			'Speed-Meter',
			'Speedy Spider',
			'SpeedySpider',
			'SPEng',
			'Spice M5460',
			'spider',
			'Spider Indexer',
			'Spider_Monkey',
			'SpiderLing',
			'SpiderMan Mozilla',
			'SpiDir.com',
			'Spinn3r',
			'Spinne',
			'SplatSearch',
			'Spock Crawler',
			'SpokeSpider',
			'spoofedhost.onlinescanner.com',
			'sportspyder',
			'spray-can',
			'Sprinklr',
			'sproose',
			'SpuhexBot',
			'SpurlBot',
			'SputnikBot',
			'spyder3',
			'spyder3.microsys.com',
			'SpyNet',
			'spyonweb',
			'sql injection',
			'SquidClamAV_Redirector',
			'SquigglebotBot',
			'Sqworm',
			'Sqworm i686-pc-linux',
			'SSL Labs',
			'SSL-Crawler',
			'SSLBot',
			'SSM Agent',
			'StackRambler',
			'staff',
			'start.exe',
			'startmebot',
			'StashBot',
			'Statastico',
			'statcrawler',
			'statdom',
			'StatoolsBot',
			'Statsbot',
			'StatusCake',
			'Steeler',
			'Stephan Kopp bot',
			'STINGbot',
			'StitcherBot',
			'storebot',
			'Storm-crawler',
			'StorygizeBot',
			'stq_bot',
			'strap',
			'Stratagems',
			'stresstest',
			'Stripper',
			'Stroke',
			'Strokebot',
			'struts-pwn',
			'StudioFACA',
			'StudioFACA Search',
			'studylib bot',
			'StumbleUpon',
			'suchen',
			'suchknecht',
			'Suck',
			'Sucker',
			'Sufog',
			'suggybot',
			'sukibot_heritrix',
			'summify',
			'Super Monitoring',
			'Superarama',
			'SuperBot',
			'superfeedr',
			'SuperHTTP',
			'SuperPagesUrlVerifyBot',
			'Supports gzip encoding',
			'Supybot',
			'SurcentroBot',
			'sureseeker',
			'Surfbot',
			'Surphace',
			'Surphace Scout',
			'suzuran',
			'SVD_TXT',
			'SWEBot',
			'SwissSearch',
			'sygol',
			'SygolBot',
			'Symfony Spider',
			'Symfony2',
			'SynHttpClient-Built',
			'SynoBot',
			'Syntryx',
			'Sysomos',
			'System.Random',
			'Szukacz',
			'T0PHackTeam',
			't6labs',
			'TA SEO Crawler',
			'taboola',
			'Tagoobot',
			'tagSeoBot',
			'tAkeOut',
			'TalkTalk',
			'taptubot',
			'Tarantula',
			'Taringa',
			'TarmotBot',
			'TeamSpeak bot',
			'Technoratibot',
			'TeeRaidBot',
			'TelegramBot',
			'telnet0',
			'temnos.com',
			'Teoma',
			'Teradex Mapper',
			'TerrawizBot',
			'test',
			'Test Certificate Info',
			'TestCrawler',
			'Testomatobot',
			'Tetrahedron',
			'The Intraformant',
			'The.Intraformant',
			'TheFreeDictionary',
			'theinternetrules',
			'TheNomad',
			'theoldreader',
			'theoldreader.com',
			'thief',
			'thieves',
			'Thinglink ImageBot',
			'THIS PC WAS TAGGED BY DR.VINCE',
			'ThisIsOurYear_Linkchecker',
			'Thumbnail.CZ robot',
			'Thumbshots',
			'ThumbShots-Bot',
			'thumbshots-de-Bot',
			'Thumbshots.ru',
			'ThumbSniper',
			'tigerbot',
			'TightTwatBot',
			'timboBot',
			'TinEye',
			'TipTop',
			'Titan',
			'TkBot',
			'Tkensaku',
			'tldstat.com crawler',
			'Toata dragostea mea pentru dia',
			'toCrawlUrlDispatcher',
			'TodoExpertosBot',
			'TomTom places company search',
			'Tools4noobs.com Spider',
			'topbloglog',
			'topicblogs',
			'Topicbot',
			'topster',
			'topster_de-crawler',
			'toquo.es',
			'Toread-Crawler',
			'touche',
			'TouTrix crawler',
			'Toweya',
			'Toweyabot',
			'Traackr',
			'TridentSpider',
			'trivial',
			'troovziBot',
			'trovator',
			'trovitBot',
			'True_Robot',
			'TrueBot',
			'truwoGPS',
			'turingos',
			'TurnitinBot',
			'TutorGigBot',
			'Tutorial Crawler',
			'tweetedtimes',
			'Tweetminster',
			'twenga',
			'TwengaBot',
			'Twiceler',
			'Twikle',
			'Twingly',
			'Twingly Recon',
			'TWMBot',
			'TygoBot',
			'Typhoeus',
			'u12Bot',
			'U2Bot',
			'UASlinkChecker',
			'ubermetrics-technologies',
			'uclassify',
			'uclassify.com',
			'UCSD-Crawler',
			'UdmSearch',
			'uipbot',
			'Ultraseek',
			'uMBot',
			'unchaos_crawler',
			'Unicorn',
			'UnisterBot',
			'Unitek UniEngine',
			'UniversalFeedParser',
			'updated',
			'Updownerbot',
			'Upflow',
			'UptimeDog',
			'UptimeRobot',
			'URL Control',
			'URLAppendBot',
			'URLChecker',
			'urlck',
			'UrlDispatcher',
			'urlfan-bot',
			'Urlfilebot (Urlbot)',
			'URLitor',
			'URLitor.com',
			'urlresolver',
			'URLSpiderPro',
			'URLSS',
			'Urlstat',
			'UrlTrends',
			'URLy',
			'URLy Warning',
			'URLy.Warning',
			'usecurio',
			'UTSE',
			'UXCrawlerBot',
			'Vacuum',
			'VadixBot',
			'Vagabondo',
			'Valet',
			'validator',
			'Valkyrie',
			'Vampire',
			'vBSEO',
			'vBSEO_',
			'VCI',
			'VCI WebViewer',
			'vebidoobot',
			'VeBot',
			'Vedma',
			'VegeBot',
			'Vegi bot',
			'Veoozbot',
			'versellie',
			'versus crawler',
			'ViDA-NYU',
			'VideoSurf_bot',
			'VigLink',
			'Virusdie crawler',
			'virustotal',
			'Visbot',
			'visionutils',
			'vitalbox',
			'vkShare',
			'VoidEYE',
			'VoilaBot',
			'voltron',
			'Vorboss Web Crawler',
			'Vortex',
			'voyager',
			'VSAgent',
			'VSB-TUO',
			'VSE',
			'vURL Online',
			'VYU2',
			'w3af',
			'W3CRobot',
			'w3dt.net httphr',
			'wangling',
			'Wappalyzer',
			'WASALive-Bot',
			'WatchMouse',
			'WBSearchBot',
			'WbSrch',
			'web-capture',
			'web-capture.net',
			'Web-Monitoring',
			'Web-sniffer',
			'Web-sniffer.me',
			'WebAlta Crawler',
			'WebarooBot',
			'Webauskunft',
			'Webauskunft.org',
			'WebAuto',
			'Webbot',
			'WebC-I.com',
			'WebCapture',
			'webceo.com',
			'webcollage',
			'WebCookies',
			'WebCopy',
			'WebCorp',
			'webcrawl.net',
			'WebCrawler',
			'WebDataCentreBot',
			'WebDoc',
			'webeaver',
			'WebEnhancer',
			'WebFerret',
			'WebFindBot',
			'WebFuck',
			'WebGather',
			'WebGo',
			'WebGo IS',
			'WebImages',
			'webinatorbot',
			'WebIndex',
			'WebIndexer',
			'webis',
			'webkit2png',
			'weblayers',
			'WebLeacher',
			'WebLinker',
			'webmastercoffee',
			'WebmasterWorldForumBot',
			'WebMoose',
			'Webnavigator',
			'WebNL',
			'WebPictures',
			'webPluck',
			'WebRankSpider',
			'WebReaper',
			'WebSauger',
			'webscreenie',
			'WebSearch',
			'WebSearch.COM.AU',
			'Webshot',
			'WebSite',
			'Website Quester',
			'Website.Quester',
			'websitepulse',
			'websitepulse checker',
			'Websnapr',
			'Webspider',
			'Websquash',
			'Webster',
			'Webster Pro',
			'Webster.Pro',
			'WebStripper',
			'WebTarantula.com Crawler',
			'Webthumb',
			'WebThumbnail',
			'WebVac',
			'WebViewer',
			'WebVulnCrawl',
			'WebVulnScan',
			'webwalk',
			'WebWalker',
			'WebWatch',
			'WebWhacker',
			'WebZIP',
			'WeCrawlForThePeace',
			'WeLikeLinks',
			'Wells_Search_II',
			'WEP_Search',
			'WEPA',
			'WeSEE',
			'WeSEE_Bot',
			'WeViKa',
			'WeViKaBot',
			'wf_crawler',
			'wf84',
			'WGETbot',
			'Whacker',
			'WhatchaBot',
			'WhatsMyIP',
			'WhatsMyIP.org',
			'WhatWeb',
			'Whibse',
			'WhizBang',
			'Who.is Bot',
			'Whoismindbot',
			'Whoiswebsitebot',
			'WhoWhere Robot',
			'Whynder',
			'Whynder Magnet',
			'WhyNoPadlock.com',
			'wibbitz',
			'Widow',
			'WikiBot',
			'WikiDo',
			'WikioFeedBot',
			'wikiwix-bot',
			'Wild Ferret Web Hopper',
			'Willow Internet Crawler',
			'WillyBot',
			'Windows-RSS-Platform',
			'WinHTTP Example',
			'WinHttpRequest Bot-Trap-Test',
			'WiniFighter',
			'WinWebBot',
			'wired-digital-newsbot',
			'wise-guys',
			'WISEbot',
			'WISENutbot',
			'WiseWire',
			'wisponbot',
			'withknown',
			'wkhtmlto',
			'WMCAI_robot',
			'wmtips',
			'wmtips.com',
			'Woko',
			'WomlpeFactory',
			'wonderbot',
			'woobot',
			'WooRank',
			'WordChampBot',
			'WordPress.com bots',
			'woriobot',
			'World web heritage',
			'WorldBrewBot',
			'WormlyBot',
			'WoTBoT',
			'WOW32',
			'WP Engine',
			'wpspydr',
			'wsAnalyzer',
			'wscheck',
			'WURFL ImageEngine',
			'WWW-Mechanize',
			'www.adressendeutschland.de',
			'www.iir.com',
			'www.osaicbt.com',
			'www.vinn.com.au',
			'WWWeasel',
			'WWWOFFLE',
			'wwwster',
			'WWWWanderer',
			'x100Bot',
			'x28-job-bot',
			'Xaldon',
			'Xaldon WebSpider',
			'Xaldon_WebSpider',
			'XaxisSemanticsClassifier',
			'Link Sleuth',
			'XGET',
			'XING-contenttabreceiver',
			'xing.com',
			'xirq',
			'XML Sitemaps Generator',
			'XmlSitemapGenerator',
			'Xombot',
			'xpymep',
			'XunBot',
			'xUSAx',
			'XYZBot',
			'Y!TunnelPro',
			'Yaanb',
			'yacy',
			'yacybot',
			'YadowsCrawler',
			'YahooSeeker',
			'YamanaLab-bot',
			'YandeG',
			'Yanga',
			'Yanga WorldSearch Bo',
			'Yasaklibot',
			'YellowLabTools',
			'Yelpbot',
			'yelpspider',
			'YesupBot',
			'Yieldbot',
			'YioopBot',
			'ynapse',
			'Yo-yo',
			'YodaoBot',
			'Yoleo',
			'Yoleo Consumer',
			'YOOBI.de bot',
			'yoozBot',
			'YottaaMonitor',
			'YottaBot',
			'YottaShopping_Bot',
			'your-search-bot',
			'youreputation',
			'yourls',
			'YowedoBot',
			'YRSpider',
			'YYSpider',
			'Z-Add Link Checker',
			'Zao',
			'Zatka',
			'Zealbot',
			'zeef.com',
			'ZeerchBot',
			'Zeller',
			'Zemanta',
			'Zeus Link Scout',
			'Zeus_',
			'ZIPCodeBuyBot',
			'ZipCommander',
			'ZipppBot',
			'ZnajdzFoto',
			'Zombiebot',
			'Zookabot',
			'ZoomInfo bot',
			'zootycoon',
			'Zuhause(ARexx)',
		);

		//bu listenin amacı bot tespit etmektir
		//asla yasaklamak değildir
		$spider_dedector = array(
			'@',
			'https:',
			'http:',
			'.org',
			'.net',
			'.com',
			'.ru',
			'.jp',
			'.ch',
			'bot',
			'crawl',
			'slurp',
			'spider',
			'seek',
			'accoona',
			'acoon',
			'adressendeutschland',
			'ah-ha.com',
			'ahoy',
			'altavista',
			'ananzi',
			'anthill',
			'appie',
			'arachnophilia',
			'arale',
			'araneo',
			'aranha',
			'architext',
			'aretha',
			'arks',
			'asterias',
			'atlocal',
			'atn',
			'atomz',
			'augurfind',
			'backrub',
			'bannana_bot',
			'baypup',
			'bdfetch',
			'big brother',
			'biglotron',
			'bjaaland',
			'blackwidow',
			'blaiz',
			'blog',
			'blo.',
			'bloodhound',
			'boitho',
			'booch',
			'bradley',
			'butterfly',
			'calif',
			'cassandra',
			'ccubee',
			'cfetch',
			'charlotte',
			'churl',
			'cienciaficcion',
			'cmc',
			'collective',
			'comagent',
			'combine',
			'computingsite',
			'csci',
			'curl',
			'cusco',
			'daumoa',
			'deepindex',
			'delorie',
			'depspid',
			'deweb',
			'die blinde kuh',
			'digger',
			'ditto',
			'dmoz',
			'docomo',
			'download express',
			'dtaagent',
			'dwcp',
			'ebiness',
			'ebingbong',
			'e-collector',
			'ejupiter',
			'emacs-w3 search engine',
			'esther',
			'evliya celebi',
			'ezresult',
			'facebook',
			'falcon',
			'felix ide',
			'ferret',
			'fecth',
			'fetchrover',
			'fido',
			'findlinks',
			'fireball',
			'fish search',
			'fouineur',
			'funnelweb',
			'gazz',
			'gcreep',
			'genieknows',
			'getterroboplus',
			'geturl',
			'glx',
			'goforit',
			'golem',
			'grabber',
			'grapnel',
			'gralon',
			'griffon',
			'gromit',
			'grub',
			'gulliver',
			'hamahakki',
			'harvest',
			'havindex',
			'helix',
			'heritrix',
			'hku www octopus',
			'homerweb',
			'htdig',
			'html index',
			'html_analyzer',
			'htmlgobble',
			'hubater',
			'hyper-decontextualizer',
			'ibm_planetwide',
			'iconsurf',
			'iltrovatore',
			'image.kapsi.net',
			'imagelock',
			'incywincy',
			'indexer',
			'infobee',
			'informant',
			'ingrid',
			'inktomisearch.com',
			'inspector web',
			'intelliagent',
			'internet shinchakubin',
			'ip3000',
			'iron33',
			'israeli-search',
			'ivia',
			'jack',
			'jakarta',
			'javabee',
			'jetbot',
			'jumpstation',
			'katipo',
			'kdd-explorer',
			'kilroy',
			'knowledge',
			'kototoi',
			'kretrieve',
			'labelgrabber',
			'lachesis',
			'larbin',
			'legs',
			'libwww',
			'linkalarm',
			'link validator',
			'linkscan',
			'lockon',
			'lwp',
			'lycos',
			'magpie',
			'mantraagent',
			'mapoftheinternet',
			'marvin/',
			'mattie',
			'mediafox',
			'mediapartners',
			'mercator',
			'merzscope',
			'microsoft url control',
			'minirank',
			'miva',
			'mj12',
			'mnogosearch',
			'monster',
			'moose',
			'motor',
			'multitext',
			'muncher',
			'muscatferret',
			'mwd.search',
			'myweb',
			'najdi',
			'nameprotect',
			'nationaldirectory',
			'nazilla',
			'ncsa beta',
			'nec-meshexplorer',
			'nederland.zoek',
			'netcarta webmap engine',
			'netmechanic',
			'netresearchserver',
			'netscoop',
			'newscan-online',
			'nhse',
			'nokia6682/',
			'nomad',
			'noyona',
			'nzexplorer',
			'objectssearch',
			'occam',
			'omni',
			'open text',
			'openfind',
			'openintelligencedata',
			'orb search',
			'osis-project',
			'pack rat',
			'pageboy',
			'pagebull',
			'page_verifier',
			'panscient',
			'parasite',
			'partnersite',
			'patric',
			'pear.',
			'pegasus',
			'peregrinator',
			'pgp key agent',
			'phantom',
			'phpdig',
			'picosearch',
			'piltdownman',
			'pimptrain',
			'pinpoint',
			'pioneer',
			'piranha',
			'plumtreewebaccessor',
			'pogodak',
			'poirot',
			'pompos',
			'poppelsdorf',
			'poppi',
			'popular iconoclast',
			'psycheclone',
			'publisher',
			'python',
			'rambler',
			'raven search',
			'roach',
			'road runner',
			'roadhouse',
			'robbie',
			'robofox',
			'robot',
			'robozilla',
			'rules',
			'salty',
			'sbider',
			'scooter',
			'scoutjet',
			'scrubby',
			'search.',
			'searchprocess',
			'semanticdiscovery',
			'senrigan',
			'sg-scout',
			'shai\'hulud',
			'shark',
			'shopwiki',
			'sidewinder',
			'sift',
			'silk',
			'simmany',
			'site searcher',
			'site valet',
			'sitetech-rover',
			'skymob.com',
			'sleek',
			'smartwit',
			'sna-',
			'snappy',
			'snooper',
			'sohu',
			'speedfind',
			'sphere',
			'sphider',
			'spinner',
			'spyder',
			'steeler/',
			'suke',
			'suntek',
			'supersnooper',
			'surfnomore',
			'sven',
			'sygol',
			'szukacz',
			'tach black widow',
			'tarantula',
			'templeton',
			'/teoma',
			't-h-u-n-d-e-r-s-t-o-n-e',
			'theophrastus',
			'titan',
			'titin',
			'tkwww',
			'toutatis',
			't-rex',
			'tutorgig',
			'twiceler',
			'twisted',
			'ucsd',
			'udmsearch',
			'url check',
			'updated',
			'vagabondo',
			'valkyrie',
			'verticrawl',
			'victoria',
			'vision-search',
			'volcano',
			'voyager/',
			'voyager-hc',
			'w3c_validator',
			'w3m2',
			'w3mir',
			'walker',
			'wallpaper',
			'wanderer',
			'wauuu',
			'wavefire',
			'web core',
			'web hopper',
			'web wombat',
			'webbandit',
			'webcatcher',
			'webcopy',
			'webfoot',
			'weblayers',
			'weblinker',
			'weblog monitor',
			'webmirror',
			'webmonkey',
			'webquest',
			'webreaper',
			'websitepulse',
			'websnarf',
			'webstolperer',
			'webvac',
			'webwalk',
			'webwatch',
			'webwombat',
			'webzinger',
			'wget',
			'whizbang',
			'whowhere',
			'wild ferret',
			'worldlight',
			'wwwc',
			'wwwster',
			'xenu',
			'xget',
			'xift',
			'xirq',
			'yandex',
			'yanga',
			'yodao',
			'zao/',
			'zippp',
			'zyborg',
		);

		//Direk izin verilen IP adreslerimiz
		$allowed_ips = array(
			//sh sunucumuz
			'178.211.56.170', '178.211.56.171', '178.211.56.172', '178.211.56.173', '178.211.56.174',
			//elluga sunucumuz
			'176.53.49.98', '176.53.49.99', '176.53.49.100', '176.53.49.101', '176.53.49.102', '176.53.49.103', '176.53.49.104',
			'176.53.49.105', '176.53.49.106', '176.53.49.107', '176.53.49.108', '176.53.49.109', '176.53.49.110',
			//cdn
			'176.53.89.167', '176.53.89.168', '176.53.89.169', '176.53.89.170',
			'176.53.89.171', '176.53.89.172', '176.53.89.173', '176.53.89.174',
		);

		//Direk yasaklanan UA
		$ua_banned = array(
			'', 				#yani tarayıcı bilgisi boş olanlar
			'Ruby',				#Rubby diliyle yazılmış programlar
			'ZmEu',				#phpmyadmin zaafiyet tarayıcı
			'Nuzzel',			#bir bot
			'www.ru',			#rus arama motoru
			'buzztalk',			#
			'Scanbot',			#
			'null',				#null boş demek ama, null ismiyle gelen bot var
			'Mozilla/5.0 Jorgee',				#varolmayan bir tam tarayıcı adı
			'Mozilla/5.0',						#varolmayan bir tam tarayıcı adı
			'Mozilla/5.0 (compatible)',			#varolmayan bir tam tarayıcı adı
			'Mozilla/5.0 (X11; Linux i686)',	#varolmayan bir tam tarayıcı adı
		);

		//gerçek ile karışabilen fake botlar
		$ua_fakes = array(
			'Facebot Twitterbot', 	#hem facebook hem twitter olduğunu iddia eden bir sahte bot
		);

	}
